### ISSUE TITLE
Clean up news?

### ISSUE THREAD

**Issue by tincancrab** [drawpile/website#1]
Is there any way to clear news before initiating this website? I'm going to try to give this one more go, but I'm getting errors on the dates in the news posts, that's what hung me up before. I'll replicate later if you need to see that. But I won't need the news, so what's the easiest way to clear out the news posts? Deleting from the cloned repository under assets made it unhappy, so I'm sure I'm missing something here.

**Comment by callaa** [comment]
The news posts are imported from the assets directory by the `update-assets.sh` script. When you first run `./manage.py migrate`, the database starts out blank. The easiest way is to just skip the update-assets script. The script also adds a bunch of images that are used on the help pages. This may also be something that you do not need.

If the error message you saw was something about "naive datetimes", then it's just a warning about missing timezone information and can safely be ignored.

One thing I've forgotten from the readme: after initializing the database, you'll probably want to run `./manage.py createsuperuser` to create an initial super user account for yourself.
