### ISSUE TITLE
Drawpile unable to Open MacOS High Sierra 

### ISSUE THREAD

**Issue by pastaandpencils** [drawpile/website#10]
I updated to Drawpile 2.0.11 after the comments were not able to open and I wasn't able to move the canvas more than zooming in and out. After updating it I have not been able to open the program since. I have updated my computer and went through all the measures to make sure that I can run the program, but no matter what I always receive this:

**Drawpile cannot be opened because of a problem.

Check with the developer to make sure Drawpile works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.**

I have already tried to uninstall and reinstall 2.0.11 but it came up with the same message. Can someone please help or y'know fix the hell out of whatever bug this is. C'mon Drawpile.

**Comment by callaa** [comment]
There was a problem with the packaging. An updated version is now up on the download page.
