### ISSUE TITLE
pen pressure not working on drawpile

### ISSUE THREAD

**Issue by fl0dh** [drawpile/website#14]
I have recently downloaded drawpile for collaborations with other artists but we just can't figure out how to enable the pen pressure. Can anyone help me?

**Comment by Bluestrings-Drawpile** [comment]
Drawpile's pen pressure settings must match your tablet. I'm assuming you're using Windows. What version of Windows are you using? (e.g. Windows 10, Windows 7, etc)

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
