### ISSUE TITLE
Brush Pointer/Caret switching to standard pointer randomly w/ 2.1.6

### ISSUE THREAD

**Issue by robparenti** [drawpile/website#16]
Hello, 

  I just upgraded to the newer 2.1.6 version. I'm having issues with a strange bug where the brush pointer region randomly turns into a normal arrow pointer.  It then stays a pointer for a while then may switch back. It occurs frequently enough to be annoying. 

I'm using a lower end tablet, Parblo A610. Removing pen **sometimes** resets the process.  Dabbing strokes - quick and with some lift off the tablet seem to trigger this faster.  It was never an issue before. The last version I had was 2.1.2 so there is the range of updates.

All the new updates and features are looking awesome. I can tell that Drawpile is a work of passion - I love using it.

Thanks for your time,
Rob

**Comment by erik90mx** [comment]
you can find the Drawpile's issue tracker here (this one is for its web page): https://github.com/drawpile/Drawpile/issues

Regards

**Comment by Bluestrings-Drawpile** [comment]
Is this still issue ongoing? Are you using Windows? 

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
