### ISSUE TITLE
Server Error (500) when I tried 2 make an account :(

### ISSUE THREAD

**Issue by kitsuko1** [drawpile/website#19]
It won't let me make an account because it keeps coming up with that error thingy instead

**Comment by callaa** [comment]
Whoops, I just fixed one bug related to this but looks like there is another one (a server misconfiguration.) I'll have it fixed soon.

**Comment by callaa** [comment]
Okay, should be fixed now. The signup message might end up in your spam folder, though, so remember to check that.

**Comment by kitsuko1** [comment]
thank uu !!!! :D
