### ISSUE TITLE
wrong description issues in communities page

### ISSUE THREAD

**Issue by neiriod** [drawpile/website#20]
1.the list server introduction is showing the wrong list server address
the right list server address is : syntheticdreams.net  

![Snipaste_2020-02-23_13-51-25](https://user-images.githubusercontent.com/49644585/75113405-c0e51100-5688-11ea-9248-b21c361ccd0a.png)

2. also the address box is showing the same wrong list server address when click the connect icon
![Snipaste_2020-02-23_13-56-45](https://user-images.githubusercontent.com/49644585/75113451-0b668d80-5689-11ea-8095-e8b55a2d3d74.png)

3. the introduction for SyntheticDreams.net has wrong info
SyntheticDreams.net is open to registered users, not unregistered users
![Snipaste_2020-02-23_09-29-33](https://user-images.githubusercontent.com/49644585/75113767-6a2d0680-568b-11ea-91a8-2bdcb20d49a9.png)

**Comment by notfood** [comment]
This is a particular misconfigured community. They have put the wrong server hostname under `Drawpile server`

KemonoFriends server works fine.

Admin panel
![image](https://user-images.githubusercontent.com/5370107/75116207-eac01880-5633-11ea-90be-14dd5974a156.png)

Community page
![image](https://user-images.githubusercontent.com/5370107/75116213-fe6b7f00-5633-11ea-8a08-bdc5b2ffa4a2.png)

**Comment by tincancrab** [comment]
This has been fixed.
