### ISSUE TITLE
Password reset, not receiving emails

### ISSUE THREAD

**Issue by perbast** [drawpile/website#25]
I've tried to reset my password several times and tried to make a new account as well and I'm not receiving any emails at all. There's nothing in my junk mail folder either.

**Comment by notfood** [comment]
What is the @server domain address you are using?

**Comment by perbast** [comment]
> 
> 
> What is the @server domain address you are using?

I was referring to the drawpile.net website but originally I tried logging on to a room at pub.drawpile.net. I couldn't remember my password so I went to drawpile.net to reset it and I'm not receiving any emails at all from the website.

**Comment by notfood** [comment]
Yeah, I'm asking the domain of your email.

Certain domains have the drawpile.net domain blocked. I want to re-route it so I need your email's domain.

**Comment by perbast** [comment]
> 
> 
> Yeah, I'm asking the domain of your email.
> 
> Certain domains have the drawpile.net domain blocked. I want to re-route it so I need your email's domain.

Oh, I see! @live.ca

**Comment by notfood** [comment]
Okay. I added it to the list of redirects. Try again.

**Comment by perbast** [comment]
> 
> 
> Okay. I added it to the list of redirects. Try again.

It worked! Thankyou so much! :)
