### ISSUE TITLE
Unable to remove alternative usernames or make a username primary. 

### ISSUE THREAD

**Issue by adsuetium** [drawpile/website#27]
Hello! I hope this is the correct place to report this. I was experimenting with what I could put as my alternative usernames for fun, and I put symbols, which has caused errors when I have tried to remove them on the website. All three of these usernames work on drawpile and there are no issues there as far as I know. 

The three alternative usernames that are causing issues are: 

%
///
lover.

They all have three separate error messages when I have tried to remove them or make them primary. 

error message for % (for both removing and setting as primary) -  SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON
![image](https://user-images.githubusercontent.com/112916098/188535805-4d3cf321-4ead-49c6-a2ad-6b1206a110a6.png)

error message for removing /// -  Error: {"detail":"Method \"DELETE\" not allowed."}
![image](https://user-images.githubusercontent.com/112916098/188535757-c698d165-2192-448e-bbae-62442333bbfb.png)

error message for setting /// as primary -  Error: {"detail":"Method \"PATCH\" not allowed."}
![image](https://user-images.githubusercontent.com/112916098/188535684-5ed829e4-71f6-4320-b19a-c4a7960b6c1c.png)

error message for lover. (for both removing and setting as primary) - Error
![image](https://user-images.githubusercontent.com/112916098/188535902-b68cab5e-8f59-4dc2-aee8-3b7c88bc6414.png)

I would actually like to keep "%" and "lover." but I would like to have the ability to remove them or make them my primary username if possible. Thank you for your time!

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This is the correct place to report it! Looks like the frontend doesn't escape a URL properly and then bangs its head against something that doesn't exist. Should be solveable.

**Comment by askmeaboutlo0m** [comment]
Whoops, Github auto-closed it. I think I fixed it, but it hasn't been rolled out yet.

**Comment by askmeaboutlo0m** [comment]
Ah heck it auto-closed it again, that's why I couldn't find it anymore. It should be fixed now anyway, if it still doesn't work, feel free to re-open the ticket.

**Comment by adsuetium** [comment]
Thank you! I will reopen if it doesn’t work.
