### ISSUE TITLE
Allow computers to draw with touchscreen?

### ISSUE THREAD

**Issue by Mintybuni** [drawpile/website#3]
I was thinking it would be useful to have a feature that allows you to draw with the touchscreen because some people may not own a tablet.  You can move the canvas around by using two fingers which also allows you zoom in/out and to rotate it, while drawing with only one finger.

**Comment by callaa** [comment]
This feature already exists. Simply uncheck the "scroll with finger" checkbox in the preferences dialog.

For future reference, please make requests related to the application in the [Drawpile issue tracker](https://github.com/drawpile/Drawpile/issues). This issue tracker is for the website.

**Comment by haluk** [comment]
I have touch screen laptop, and I unchecked "scroll with finger" but still can't draw anything on canvas.
