### ISSUE TITLE
(Feature?) NSFW Session invite links.

### ISSUE THREAD

**Issue by amoruwu** [drawpile/website#34]
To limit liability, Session links or Invites that lead to NSFW boards should have a warning as when viewing a NSFW community for the first time.

![image](https://github.com/drawpile/website/assets/78520579/936a59ba-60c8-4619-aa59-d40fdeb373d6)
 
_Drawpile isn't responsible for what's going on in the session behind the link above. This page just provides a shortcut for convenience._ Does limit liability but it's not such an obvious warning, as the I'm 18 years or older page. If the warning couldn't be placed behind the invite shortcut. A more obvious piece of text, could perhaps be considered! 
![image](https://github.com/drawpile/website/assets/78520579/d1f7105d-6466-443d-b837-423be353d285)

**Comment by askmeaboutlo0m** [comment]
Drawpile itself already warns you when you attempt to join a session marked NSFM, so I don't think an extra confirmation page is warranted, you'd just be clicking through the same warning twice. However, showing an extra warning text like in the second example would be fine. It'd probably be a piece of information embedded into the link itself, so that it's only shown when relevant.

![image](https://github.com/drawpile/website/assets/13625824/ded65e1a-098d-4b5b-bad2-cc6f9e654e38)

**Comment by amoruwu** [comment]
Huh, That must be a 2.2 server thing since I don't/haven't seen the warning beforehand.  
Thank you for the confirmation.

**Comment by amoruwu** [comment]
perhaps the extra confirmation page could be warranted since it only shows up once. And would save people time of opening drawpile/ would be useful for when you can open sessions on web.  

Thank you for the confirmation.

**Comment by askmeaboutlo0m** [comment]
It's a 2.2 *client* thing. You may have turned it off, it's the "warn when joining NSFM sessions" in the parental controls settings. The web client also shows this message in the login process.

I think having a message at the bottom would be sufficient, there's no particular benefit to making you click through two warning pages.

**Comment by amoruwu** [comment]
Oh yeah, Most likely. 

Message at the bottom would be sufficient. This issue can be closed.

**Comment by askmeaboutlo0m** [comment]
The issue can be closed when it's implemented! So not yet.

**Comment by askmeaboutlo0m** [comment]
This is implemented now. Starting with Drawpile 2.0.1, invite links will include an nsfm flag if the session is tagged as such. Same goes for the session listing pages in the community pages and any list server that updates to this version.

Thanks for suggesting!

![image](https://github.com/drawpile/website/assets/13625824/0023b795-cf2e-48b7-bc4c-45b1b7718b3e)
