### ISSUE TITLE
Connection problems, I think?

### ISSUE THREAD

**Issue by Dissociation** [drawpile/website#5]
I open up drawpile and can select and join a few of the rooms. However the majority of the most popular ones come up with a pop up saying "Invalid state!" This didn't used to happen as I was able to join them weeks before?

**Comment by callaa** [comment]
Are you using the latest version? If you're using a version older than 2.0.6, that error is seen when logging into a session with a reserved username. If you're using a newer version, then it's a new bug. If you open the log file (via the Help menu) there should be a dump of the login handshake. Can you post that part?

**Comment by Dissociation** [comment]
I'm using 2.0.5 so the version might be an issue. I'll try downloading the latest version and see if that works.
