### ISSUE TITLE
tablet 

### ISSUE THREAD

**Issue by PoofyDragon** [drawpile/website#6]
so this only happens on drawpile for some reason and idk how to fix it
sometimes it appears, sometimes it doesnt
when i try to draw it makes a white circle around my cursor and would draw a straight line after
if i would try and draw a curved line, it would be straight lines
its not smooth 
![image](https://user-images.githubusercontent.com/30249603/37571528-f0c84f96-2aba-11e8-9074-1e47b3d02d01.png)

**Comment by callaa** [comment]
Sounds like it's activating a pen gesture. Check this link: [How to get rid of those annoying circles from your wacom cursor in Windows 7](http://www.volnapc.com/all-posts/how-to-get-rid-of-those-annoying-circles-from-your-wacom-cursor-in-windows-7)

Side note: this issue tracker is for the website. Issues regarding the application itself should be made to the [Drawpile](https://github.com/drawpile/Drawpile/issues) issue tracker.
