### ISSUE TITLE
missing favicon in the website

### ISSUE THREAD

**Issue by leandro2222** [drawpile/website#8]
I know this isn't the best place for this post but I don't know how to proper post it elsewhere.

So, I suggest to add this piece of code inside the `<head>` tags of the website:
`<link rel="icon" type="image/png" href="./16x16.png" sizes="16x16">`
`<link rel="icon" type="image/png" href="./32x32.png" sizes="32x32">`
`<link rel="icon" type="image/png" href="./48x48.png" sizes="48x48">`

Alternatively, you can use and declare the favicon.ico (multiple sizes of the icon in a single file):
`<link rel="icon" href="./favicon.ico">`

_(ps: usually the browsers can automatically find the favicon.ico when in root folder, without the declaration)_

Icons avaible for download in the link: https://mega.nz/#!UQQjDRgR!iROFUW8OKn3V9tWKwmjjh537vUon_aqm1QHCBxSOE9w

**Comment by callaa** [comment]
Thank you! I added the favicons to the website. This issue tracker is just the right place for this kinds of posts.
